title: BigHammer
description: A starter template for a Jekyll site using the Just the Docs theme!
theme: just-the-docs

# Use the base URL of your site:
url: http://127.0.0.1:4000 
baseurl: ""              

